name: Generate GitHub Stats

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate metrics
        uses: anuraghazra/github-readme-stats@production
        with:
          username: YinoXu
          commit_message: Updated with latest metrics
          output_folder: "."

