name: Generate GitHub Stats

on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day at 12:00am
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate metrics
        uses: anuraghazra/github-readme-stats@production
        with:
          username: YinoXu
          commit_message: Updated with latest metrics
          output_folder: "."

